import { type InsertProduct } from "@shared/schema";

// Sample products with pre-computed embeddings (in a real app, these would be generated by ML model)
export const sampleProducts: InsertProduct[] = [
  // Fashion (10 products)
  {
    name: "Designer Leather Handbag",
    description: "Premium Italian leather handbag with gold hardware and adjustable strap",
    category: "Fashion",
    price: 299.99,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.5,
    reviewCount: 128,
    embeddings: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  },
  {
    name: "Classic Denim Jacket",
    description: "Vintage-style denim jacket with distressed finish and multiple pockets",
    category: "Fashion",
    price: 89.99,
    imageUrl: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.2,
    reviewCount: 89,
    embeddings: [0.2, 0.1, 0.4, 0.3, 0.6, 0.5, 0.8, 0.7, 1.0, 0.9]
  },
  {
    name: "Premium Cotton T-Shirt",
    description: "Soft organic cotton t-shirt with perfect fit and fade-resistant colors",
    category: "Fashion",
    price: 34.99,
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.7,
    reviewCount: 245,
    embeddings: [0.3, 0.4, 0.1, 0.2, 0.7, 0.8, 0.5, 0.6, 0.9, 1.0]
  },
  {
    name: "Designer Sneakers",
    description: "Limited edition sneakers with premium materials and comfortable sole",
    category: "Fashion",
    price: 159.99,
    imageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.4,
    reviewCount: 156,
    embeddings: [0.4, 0.3, 0.2, 0.1, 0.8, 0.7, 0.6, 0.5, 1.0, 0.9]
  },
  {
    name: "Wool Blend Scarf",
    description: "Luxurious wool blend scarf with cashmere touch and elegant patterns",
    category: "Fashion",
    price: 45.99,
    imageUrl: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.3,
    reviewCount: 67,
    embeddings: [0.5, 0.6, 0.3, 0.4, 0.9, 1.0, 0.7, 0.8, 0.1, 0.2]
  },
  {
    name: "Silk Evening Dress",
    description: "Elegant silk evening dress with flowing silhouette and delicate details",
    category: "Fashion",
    price: 199.99,
    imageUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.8,
    reviewCount: 92,
    embeddings: [0.6, 0.5, 0.4, 0.3, 1.0, 0.9, 0.8, 0.7, 0.2, 0.1]
  },
  {
    name: "Leather Belt",
    description: "Genuine leather belt with classic buckle and adjustable length",
    category: "Fashion",
    price: 59.99,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.1,
    reviewCount: 34,
    embeddings: [0.7, 0.8, 0.5, 0.6, 0.1, 0.2, 0.9, 1.0, 0.3, 0.4]
  },
  {
    name: "Cashmere Sweater",
    description: "Ultra-soft cashmere sweater with ribbed cuffs and hem",
    category: "Fashion",
    price: 129.99,
    imageUrl: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.6,
    reviewCount: 78,
    embeddings: [0.8, 0.7, 0.6, 0.5, 0.2, 0.1, 1.0, 0.9, 0.4, 0.3]
  },
  {
    name: "Athletic Running Shoes",
    description: "High-performance running shoes with advanced cushioning technology",
    category: "Fashion",
    price: 119.99,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.5,
    reviewCount: 203,
    embeddings: [0.9, 1.0, 0.7, 0.8, 0.3, 0.4, 0.1, 0.2, 0.5, 0.6]
  },
  {
    name: "Designer Sunglasses",
    description: "Premium polarized sunglasses with UV protection and scratch-resistant coating",
    category: "Fashion",
    price: 189.99,
    imageUrl: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.4,
    reviewCount: 145,
    embeddings: [1.0, 0.9, 0.8, 0.7, 0.4, 0.3, 0.2, 0.1, 0.6, 0.5]
  },

  // Electronics (10 products)
  {
    name: "Premium Smartphone Pro",
    description: "Latest flagship smartphone with advanced camera system and 5G connectivity",
    category: "Electronics",
    price: 899.99,
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.6,
    reviewCount: 1024,
    embeddings: [0.1, 0.3, 0.2, 0.4, 0.5, 0.7, 0.6, 0.8, 0.9, 1.0]
  },
  {
    name: "Wireless Earbuds Pro",
    description: "True wireless earbuds with active noise cancellation and premium sound",
    category: "Electronics",
    price: 249.99,
    imageUrl: "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.5,
    reviewCount: 567,
    embeddings: [0.2, 0.4, 0.1, 0.3, 0.6, 0.8, 0.5, 0.7, 1.0, 0.9]
  },
  {
    name: "Ultra-Thin Laptop",
    description: "Powerful laptop with retina display and all-day battery life",
    category: "Electronics",
    price: 1299.99,
    imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.7,
    reviewCount: 432,
    embeddings: [0.3, 0.1, 0.4, 0.2, 0.7, 0.5, 0.8, 0.6, 0.9, 1.0]
  },
  {
    name: "Professional Tablet",
    description: "High-performance tablet perfect for creative professionals with stylus support",
    category: "Electronics",
    price: 799.99,
    imageUrl: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.4,
    reviewCount: 289,
    embeddings: [0.4, 0.2, 0.3, 0.1, 0.8, 0.6, 0.7, 0.5, 1.0, 0.9]
  },
  {
    name: "Smart Watch Series X",
    description: "Advanced smartwatch with health monitoring and fitness tracking",
    category: "Electronics",
    price: 399.99,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.3,
    reviewCount: 178,
    embeddings: [0.5, 0.3, 0.2, 0.4, 0.9, 0.7, 0.6, 0.8, 0.1, 1.0]
  },
  {
    name: "Wireless Headphones",
    description: "Over-ear wireless headphones with superior sound quality and comfort",
    category: "Electronics",
    price: 199.99,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.6,
    reviewCount: 345,
    embeddings: [0.6, 0.4, 0.1, 0.3, 1.0, 0.8, 0.5, 0.7, 0.2, 0.9]
  },
  {
    name: "Gaming Console",
    description: "Next-generation gaming console with 4K graphics and fast loading",
    category: "Electronics",
    price: 499.99,
    imageUrl: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.8,
    reviewCount: 892,
    embeddings: [0.7, 0.5, 0.4, 0.2, 0.1, 0.9, 0.8, 0.6, 0.3, 1.0]
  },
  {
    name: "4K Webcam",
    description: "Professional 4K webcam with auto-focus and noise cancellation",
    category: "Electronics",
    price: 149.99,
    imageUrl: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.2,
    reviewCount: 123,
    embeddings: [0.8, 0.6, 0.3, 0.1, 0.2, 1.0, 0.9, 0.5, 0.4, 0.7]
  },
  {
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with 360-degree sound and waterproof design",
    category: "Electronics",
    price: 79.99,
    imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.1,
    reviewCount: 89,
    embeddings: [0.9, 0.7, 0.2, 0.4, 0.3, 0.1, 1.0, 0.8, 0.5, 0.6]
  },
  {
    name: "USB-C Hub",
    description: "Multi-port USB-C hub with HDMI, USB 3.0, and fast charging support",
    category: "Electronics",
    price: 59.99,
    imageUrl: "https://images.unsplash.com/photo-1625842268584-8f3296236761?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.0,
    reviewCount: 67,
    embeddings: [1.0, 0.8, 0.1, 0.3, 0.4, 0.2, 0.9, 0.7, 0.6, 0.5]
  },

  // Home Decor (10 products)
  {
    name: "Modern Table Lamp",
    description: "Minimalist table lamp with adjustable brightness and USB charging port",
    category: "Home Decor",
    price: 79.99,
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.5,
    reviewCount: 156,
    embeddings: [0.1, 0.4, 0.3, 0.2, 0.5, 0.8, 0.7, 0.6, 0.9, 1.0]
  },
  {
    name: "Ceramic Vase Set",
    description: "Handcrafted ceramic vases in modern geometric shapes",
    category: "Home Decor",
    price: 49.99,
    imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.3,
    reviewCount: 78,
    embeddings: [0.2, 0.3, 0.4, 0.1, 0.6, 0.7, 0.8, 0.5, 1.0, 0.9]
  },
  {
    name: "Abstract Wall Art",
    description: "Contemporary abstract wall art print on premium canvas",
    category: "Home Decor",
    price: 89.99,
    imageUrl: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.6,
    reviewCount: 134,
    embeddings: [0.3, 0.2, 0.1, 0.4, 0.7, 0.6, 0.5, 0.8, 0.9, 1.0]
  },
  {
    name: "Decorative Mirror",
    description: "Round decorative mirror with gold frame and beveled edges",
    category: "Home Decor",
    price: 119.99,
    imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.4,
    reviewCount: 89,
    embeddings: [0.4, 0.1, 0.2, 0.3, 0.8, 0.5, 0.6, 0.7, 1.0, 0.9]
  },
  {
    name: "Luxury Candle Set",
    description: "Premium scented candles in elegant glass containers with wooden wicks",
    category: "Home Decor",
    price: 65.99,
    imageUrl: "https://images.unsplash.com/photo-1602874801006-3d8b9b0c4e92?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.7,
    reviewCount: 167,
    embeddings: [0.5, 0.2, 0.3, 0.4, 0.9, 0.6, 0.7, 0.8, 0.1, 1.0]
  },
  {
    name: "Throw Pillow Set",
    description: "Set of decorative throw pillows with premium fabric and hidden zippers",
    category: "Home Decor",
    price: 39.99,
    imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.2,
    reviewCount: 95,
    embeddings: [0.6, 0.3, 0.4, 0.1, 1.0, 0.7, 0.8, 0.5, 0.2, 0.9]
  },
  {
    name: "Indoor Plant Pot",
    description: "Modern ceramic plant pot with drainage system and matching saucer",
    category: "Home Decor",
    price: 29.99,
    imageUrl: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.1,
    reviewCount: 56,
    embeddings: [0.7, 0.4, 0.1, 0.2, 0.3, 0.8, 0.9, 0.6, 0.5, 1.0]
  },
  {
    name: "Wall Clock Modern",
    description: "Minimalist wall clock with silent movement and sleek design",
    category: "Home Decor",
    price: 44.99,
    imageUrl: "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.3,
    reviewCount: 72,
    embeddings: [0.8, 0.5, 0.2, 0.3, 0.4, 0.9, 1.0, 0.7, 0.6, 0.1]
  },
  {
    name: "Pendant Light Fixture",
    description: "Modern pendant light with adjustable height and warm LED bulb",
    category: "Home Decor",
    price: 99.99,
    imageUrl: "https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.6,
    reviewCount: 123,
    embeddings: [0.9, 0.6, 0.3, 0.4, 0.5, 1.0, 0.1, 0.8, 0.7, 0.2]
  },
  {
    name: "Area Rug Premium",
    description: "Handwoven area rug with geometric patterns and soft texture",
    category: "Home Decor",
    price: 159.99,
    imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.4,
    reviewCount: 89,
    embeddings: [1.0, 0.7, 0.4, 0.5, 0.6, 0.1, 0.2, 0.9, 0.8, 0.3]
  },

  // Furniture (10 products)
  {
    name: "Ergonomic Office Chair",
    description: "Premium office chair with lumbar support and adjustable height",
    category: "Furniture",
    price: 299.99,
    imageUrl: "https://images.unsplash.com/photo-1586024229174-4293dd8af128?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.5,
    reviewCount: 234,
    embeddings: [0.1, 0.5, 0.4, 0.3, 0.2, 0.6, 0.7, 0.8, 0.9, 1.0]
  },
  {
    name: "Modern Coffee Table",
    description: "Glass-top coffee table with sleek metal frame and storage shelf",
    category: "Furniture",
    price: 189.99,
    imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.3,
    reviewCount: 145,
    embeddings: [0.2, 0.6, 0.3, 0.4, 0.1, 0.7, 0.8, 0.5, 1.0, 0.9]
  },
  {
    name: "Dining Table Set",
    description: "Solid wood dining table set for 6 with matching chairs",
    category: "Furniture",
    price: 599.99,
    imageUrl: "https://images.unsplash.com/photo-1549497538-303791108f95?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.7,
    reviewCount: 167,
    embeddings: [0.3, 0.7, 0.2, 0.5, 0.4, 0.8, 0.9, 0.6, 0.1, 1.0]
  },
  {
    name: "Velvet Sofa",
    description: "Luxurious velvet sofa with deep seating and brass legs",
    category: "Furniture",
    price: 899.99,
    imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.6,
    reviewCount: 198,
    embeddings: [0.4, 0.8, 0.1, 0.6, 0.5, 0.9, 1.0, 0.7, 0.2, 0.3]
  },
  {
    name: "Bookshelf Unit",
    description: "5-tier wooden bookshelf with adjustable shelves and modern design",
    category: "Furniture",
    price: 149.99,
    imageUrl: "https://images.unsplash.com/photo-1586024229174-4293dd8af128?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.2,
    reviewCount: 87,
    embeddings: [0.5, 0.9, 0.2, 0.7, 0.6, 1.0, 0.1, 0.8, 0.3, 0.4]
  },
  {
    name: "Accent Chair",
    description: "Mid-century modern accent chair with comfortable cushioning",
    category: "Furniture",
    price: 249.99,
    imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.4,
    reviewCount: 112,
    embeddings: [0.6, 1.0, 0.3, 0.8, 0.7, 0.1, 0.2, 0.9, 0.4, 0.5]
  },
  {
    name: "Standing Desk",
    description: "Height-adjustable standing desk with memory presets and cable management",
    category: "Furniture",
    price: 399.99,
    imageUrl: "https://images.unsplash.com/photo-1549497538-303791108f95?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.5,
    reviewCount: 203,
    embeddings: [0.7, 0.1, 0.4, 0.9, 0.8, 0.2, 0.3, 1.0, 0.5, 0.6]
  },
  {
    name: "Storage Ottoman",
    description: "Multi-functional storage ottoman with soft upholstery and hidden compartment",
    category: "Furniture",
    price: 69.99,
    imageUrl: "https://images.unsplash.com/photo-1586024229174-4293dd8af128?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.1,
    reviewCount: 45,
    embeddings: [0.8, 0.2, 0.5, 1.0, 0.9, 0.3, 0.4, 0.1, 0.6, 0.7]
  },
  {
    name: "Nightstand Drawer",
    description: "Modern nightstand with drawer and open shelf for bedroom storage",
    category: "Furniture",
    price: 89.99,
    imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.3,
    reviewCount: 76,
    embeddings: [0.9, 0.3, 0.6, 0.1, 1.0, 0.4, 0.5, 0.2, 0.7, 0.8]
  },
  {
    name: "Bar Stool Set",
    description: "Set of 2 adjustable bar stools with swivel seats and footrest",
    category: "Furniture",
    price: 179.99,
    imageUrl: "https://images.unsplash.com/photo-1549497538-303791108f95?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.2,
    reviewCount: 98,
    embeddings: [1.0, 0.4, 0.7, 0.2, 0.1, 0.5, 0.6, 0.3, 0.8, 0.9]
  },

  // Accessories (10 products)
  {
    name: "Leather Wallet",
    description: "Handcrafted genuine leather wallet with RFID blocking technology",
    category: "Accessories",
    price: 79.99,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.4,
    reviewCount: 123,
    embeddings: [0.1, 0.6, 0.5, 0.4, 0.3, 0.7, 0.8, 0.9, 1.0, 0.2]
  },
  {
    name: "Gold Necklace",
    description: "14k gold chain necklace with delicate pendant and secure clasp",
    category: "Accessories",
    price: 199.99,
    imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.6,
    reviewCount: 189,
    embeddings: [0.2, 0.7, 0.6, 0.5, 0.4, 0.8, 0.9, 1.0, 0.1, 0.3]
  },
  {
    name: "Titanium Watch",
    description: "Precision titanium watch with sapphire crystal and water resistance",
    category: "Accessories",
    price: 349.99,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.8,
    reviewCount: 234,
    embeddings: [0.3, 0.8, 0.7, 0.6, 0.5, 0.9, 1.0, 0.1, 0.2, 0.4]
  },
  {
    name: "Silk Tie",
    description: "Pure silk necktie with classic pattern and perfect width",
    category: "Accessories",
    price: 49.99,
    imageUrl: "https://images.unsplash.com/photo-1594736797933-d0d3648851f8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.3,
    reviewCount: 67,
    embeddings: [0.4, 0.9, 0.8, 0.7, 0.6, 1.0, 0.1, 0.2, 0.3, 0.5]
  },
  {
    name: "Leather Briefcase",
    description: "Professional leather briefcase with laptop compartment and shoulder strap",
    category: "Accessories",
    price: 229.99,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.5,
    reviewCount: 156,
    embeddings: [0.5, 1.0, 0.9, 0.8, 0.7, 0.1, 0.2, 0.3, 0.4, 0.6]
  },
  {
    name: "Designer Backpack",
    description: "Waterproof designer backpack with multiple compartments and USB port",
    category: "Accessories",
    price: 139.99,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.4,
    reviewCount: 178,
    embeddings: [0.6, 0.1, 1.0, 0.9, 0.8, 0.2, 0.3, 0.4, 0.5, 0.7]
  },
  {
    name: "Cufflinks Set",
    description: "Sterling silver cufflinks with elegant design and gift box",
    category: "Accessories",
    price: 89.99,
    imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.2,
    reviewCount: 43,
    embeddings: [0.7, 0.2, 0.1, 1.0, 0.9, 0.3, 0.4, 0.5, 0.6, 0.8]
  },
  {
    name: "Pearl Earrings",
    description: "Freshwater pearl earrings with sterling silver posts and backs",
    category: "Accessories",
    price: 119.99,
    imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.7,
    reviewCount: 134,
    embeddings: [0.8, 0.3, 0.2, 0.1, 1.0, 0.4, 0.5, 0.6, 0.7, 0.9]
  },
  {
    name: "Travel Jewelry Case",
    description: "Compact jewelry organizer with velvet compartments and mirror",
    category: "Accessories",
    price: 39.99,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.1,
    reviewCount: 89,
    embeddings: [0.9, 0.4, 0.3, 0.2, 0.1, 0.5, 0.6, 0.7, 0.8, 1.0]
  },

  // Additional Home items (10 products)
  {
    name: "Smart Coffee Maker",
    description: "Programmable coffee maker with app control and thermal carafe",
    category: "Home",
    price: 129.99,
    imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.5,
    reviewCount: 267,
    embeddings: [0.1, 0.7, 0.6, 0.5, 0.4, 0.8, 0.9, 1.0, 0.2, 0.3]
  },
  {
    name: "Air Purifier",
    description: "HEPA air purifier with quiet operation and smart air quality monitoring",
    category: "Home",
    price: 199.99,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.4,
    reviewCount: 189,
    embeddings: [0.2, 0.8, 0.7, 0.6, 0.5, 0.9, 1.0, 0.1, 0.3, 0.4]
  },
  {
    name: "Robot Vacuum",
    description: "Smart robot vacuum with mapping technology and app control",
    category: "Home",
    price: 299.99,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.3,
    reviewCount: 345,
    embeddings: [0.3, 0.9, 0.8, 0.7, 0.6, 1.0, 0.1, 0.2, 0.4, 0.5]
  },
  {
    name: "Humidifier",
    description: "Ultrasonic humidifier with essential oil diffuser and LED lighting",
    category: "Home",
    price: 59.99,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.2,
    reviewCount: 156,
    embeddings: [0.4, 1.0, 0.9, 0.8, 0.7, 0.1, 0.2, 0.3, 0.5, 0.6]
  },
  {
    name: "Electric Kettle",
    description: "Stainless steel electric kettle with temperature control and keep-warm function",
    category: "Home",
    price: 79.99,
    imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.6,
    reviewCount: 234,
    embeddings: [0.5, 0.1, 1.0, 0.9, 0.8, 0.2, 0.3, 0.4, 0.6, 0.7]
  },
  {
    name: "Smart Thermostat",
    description: "WiFi-enabled smart thermostat with energy saving features",
    category: "Home",
    price: 179.99,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.7,
    reviewCount: 298,
    embeddings: [0.6, 0.2, 0.1, 1.0, 0.9, 0.3, 0.4, 0.5, 0.7, 0.8]
  },
  {
    name: "Blender Pro",
    description: "High-power blender with multiple speed settings and glass pitcher",
    category: "Home",
    price: 149.99,
    imageUrl: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.5,
    reviewCount: 167,
    embeddings: [0.7, 0.3, 0.2, 0.1, 1.0, 0.4, 0.5, 0.6, 0.8, 0.9]
  },
  {
    name: "Essential Oil Diffuser",
    description: "Ultrasonic essential oil diffuser with color-changing LED lights",
    category: "Home",
    price: 39.99,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.3,
    reviewCount: 123,
    embeddings: [0.8, 0.4, 0.3, 0.2, 0.1, 0.5, 0.6, 0.7, 0.9, 1.0]
  },
  {
    name: "Smart Scale",
    description: "Digital bathroom scale with body composition analysis and app sync",
    category: "Home",
    price: 49.99,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.1,
    reviewCount: 89,
    embeddings: [0.9, 0.5, 0.4, 0.3, 0.2, 0.6, 0.7, 0.8, 1.0, 0.1]
  },
  {
    name: "Food Processor",
    description: "Multi-function food processor with various blades and large capacity bowl",
    category: "Home",
    price: 119.99,
    imageUrl: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    rating: 4.4,
    reviewCount: 145,
    embeddings: [1.0, 0.6, 0.5, 0.4, 0.3, 0.7, 0.8, 0.9, 0.1, 0.2]
  }
];
